global:
  domain: <cluster>.kyma.ondemand.com
  imagePullSecret:
    name: regcred
srv:
  bindings:
    auth:
      serviceInstanceName: xsuaa
    destinations:
      serviceInstanceName: destinations
  image:
    repository: jmsrpp/api-federation-cap
    tag: latest
  resources:
    limits:
      cpu: 100m
      ephemeral-storage: 1G
      memory: 500M
    requests:
      cpu: 100m
      ephemeral-storage: 1G
      memory: 500M
  health_check:
    liveness:
      path: /
    readiness:
      path: /
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: api-federation
  config: xs-security.json
destinations:
  serviceOfferingName: destination
  servicePlanName: lite
  parameters:
    version: 1.0.0
