apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "web-application.fullname" . }}
  labels: {{- include "web-application.labels" . | nindent 4 }}
spec:
  action: ALLOW
  selector:
    matchLabels:
      {{- include "web-application.selectorLabels" . | nindent 6 }}
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
            requestPrincipals:
              - "https://sts.windows.net/<Azure tenant ID>/*"
                
